### ISSUE TITLE
"Meetup" exercise - test runner can't compile program

### ISSUE THREAD

**Issue by v1taly-m** [exercism/cpp-test-runner#48]
![Screenshot 2021-12-23 at 19-13-07 Exercism](https://user-images.githubusercontent.com/51537473/147272641-fe01692e-9bef-432d-a310-04d80d7c2468.png)

locally it runs fine.

May be some additional data needed to solve this issue?

**Comment by patricksjackson** [comment]
https://github.com/exercism/cpp/pull/495, which I just went ahead and merged, should solve the issue once it is rolled out.

**Comment by JesApp** [comment]
This error persists. Or rather it occurs for the "gigaseconds" exercise as well, see e.g. [this solution](https://exercism.org/tracks/cpp/exercises/gigasecond/solutions/AmjadHD).

Has https://github.com/exercism/cpp/pull/495 been rolled out yet? How can I find that out?

**Comment by v1taly-m** [comment]
Fixed. Some time ago I passed the tests and complete the exercise.
